flowchart LR
    r3f_card_table_showcase_src_App_tsx(["App.tsx"])
    r3f_card_table_showcase_src_ProceduralAudio_ts["ProceduralAudio.ts"]
    r3f_card_table_showcase_src_App_tsx --> r3f_card_table_showcase_src_ProceduralAudio_ts
    r3f_card_table_showcase_src_components_Card3D_tsx["Card3D.tsx"]
    r3f_card_table_showcase_src_App_tsx --> r3f_card_table_showcase_src_components_Card3D_tsx